// Personnages doublés (Gradium Voice Design) et leurs répliques par événement de course.
// Source unique : `npm run voices` génère public/voices/<perso>/<event>_<n>.mp3 + manifest.json.
// Répliques courtes (< 100 caractères) : ça doit claquer pendant la course, pas raconter une histoire.

export const CHARACTERS = {
  reggae: {
    name: 'Riddim',
    prompt: "Voix masculine jamaïcaine qui parle français, 25 à 35 ans, chaude et solaire, accent créole des îles, rythme chaloupé, grand sourire, très enthousiaste et cool.",
    lines: {
      start: ['Yeah man, on décolle !', 'Allez, on roule en rythme, frère !', "Le curseur veut ma peau ? Il va danser d'abord !", 'Riddim est dans la place, attache ta ceinture !'],
      tempo: ['Ça accélère, man ! Garde le groove !', 'Le tempo monte, les pattes suivent !', 'Plus vite, plus chaud, yeah !', 'Oh, la basse cogne plus fort là !'],
      world: ['Nouveau monde, nouvelle vibe !', 'Wow, regarde-moi ce paysage, man !', 'On change de décor, pas de rythme !', 'Téléportation soleil, yeah !'],
      parry: ['Esquive, esquive, bye bye !', 'Trop smooth pour toi, man !', 'Parade parfaite, respect !', 'Hop, renvoyé à la maison !', 'Même pas mal, frère !'],
      boost: ['Turbo reggae, on vole !', 'Wouh, ça fuse !', "Accroche-toi, ça part fort !"],
      coins: ['Ça pleut des pièces, man !', "Jackpot sous le soleil !", 'Les pièces aiment mon groove !'],
      fever: ['FRÉNÉSIE ! Tout le monde danse !', 'Le feu, man, le feu !', 'Mode fiesta activé !'],
      hit: ['Aïe, ça pique !', 'Oups, pas grave, on repart !', 'Ouch, je reste cool, je reste cool !', 'Relève-toi, lion !'],
      lastLife: ['Dernière vie, man, concentration !', 'Plus le droit à l\'erreur, on respire !', 'Tout ou rien maintenant, frère !'],
      danger: ['Il est juste derrière, cours !', 'Le curseur me colle, vite, vite !', 'Non non non, pas mon onglet !', 'Accélère, il arrive !'],
      escape: ['Ouf, on l\'a semé !', 'Trop lent, monsieur le curseur !', 'Respire… on est bien.'],
      record: ['NOUVEAU RECORD, yeah man !', 'Record battu, la légende continue !', 'Plus loin que jamais, respect !'],
      boss: ['Oh, un gros costaud en vue !', 'Un boss ? On va le faire danser !', 'Attention, grosse vibe en approche !'],
      bossDown: ['Boss au tapis, yeah !', 'Trop fort pour toi, big boss !', 'Victoire au soleil !'],
      bossEscaped: ['Il a filé, la prochaine fois !', 'Pfiou, il s\'est sauvé !'],
      fall: ['Noooon, je tombe !', 'Oh non, le vide, man !'],
      over: ['Encore une, man, on y retourne !', 'Pas grave, le prochain run est le bon !', 'Tu y étais presque, relance !', 'Allez, une dernière… et après une autre !'],
      overRecord: ['Record de folie ! Tu peux faire mieux ? Vas-y !', 'Nouveau record ! Allez, on le pulvérise !'],
    },
  },
  classic: {
    name: 'Dino Classique',
    prompt: "Voix masculine jeune, un peu nasillarde et espiègle, style héros de jeu vidéo rétro 8-bit, sarcastique et drôle, débit rapide et plein d'énergie comique.",
    lines: {
      start: ['Pas de connexion ? Pas de problème. Go !', "Le dino hors-ligne reprend du service !", 'Mode avion, mode course !', 'Tu fermes pas mon onglet, toi !'],
      tempo: ['Ça va plus vite, ça, non ?', 'Vitesse supérieure, pixel par pixel !', 'Mes petites pattes chauffent !', 'Plus de fps, plus de fun !'],
      world: ['Oh, un nouveau niveau !', 'Chargement terminé, on continue !', "C'est quoi ce monde ? J'adore !", 'Nouvelle map débloquée !'],
      parry: ['Parade ! Trop facile.', 'Bloqué, comme un captcha !', 'Hop, erreur 404 : attaque introuvable !', 'Même pas touché !', 'Next !'],
      boost: ['Boost ! Téléchargement accéléré !', 'Wooosh !', 'Fibre optique activée !'],
      coins: ['Pièces, pièces, pièces !', 'Combo de pièces, ding ding ding !', 'Mon porte-monnaie adore ça !'],
      fever: ['FRÉNÉSIE ! Tout pète !', 'Mode turbo 8-bit !', 'Overclock total !'],
      hit: ['Aïe ! Bug !', 'Ouille, lag !', 'Hé, c\'était pas prévu ça !', 'Ctrl Z, Ctrl Z !'],
      lastLife: ['Batterie faible, dernière vie !', 'Un seul cœur, pas de bêtise !', 'Game over imminent, concentre-toi !'],
      danger: ['Le curseur ! Il va cliquer !', 'Au secours, il vise la croix !', 'Cours, cours, cours !', 'Pas la croix rouge, pitié !'],
      escape: ['Ha, raté, curseur !', 'Semé ! Trop lent, la souris.', 'Ouf, sauvegarde réussie.'],
      record: ['NOUVEAU RECORD !', 'High score explosé !', 'Record battu, capture d\'écran !'],
      boss: ['Boss en approche, sauvegardez !', 'Un boss sauvage apparaît !', 'Oh, un gros sprite !'],
      bossDown: ['Boss vaincu ! Succès débloqué !', 'K.O. !', 'Supprimé, le boss !'],
      bossEscaped: ['Il a fui, le lâche !', 'Il a fermé son onglet, lui.'],
      fall: ['Aaaah, hors de la map !', 'Pas de sol ? Sérieux ?'],
      over: ['Recommencer ? Évidemment !', 'Appuie sur espace, on repart !', 'Tu y étais presque, encore une !', 'Game over… pour cinq secondes !'],
      overRecord: ['High score ! Tu peux le battre encore ?', 'Record ! Allez, un run de plus !'],
    },
  },
  neon: {
    name: 'Néon',
    prompt: "Voix féminine jeune, streameuse gaming cyberpunk hyper énergique, débit très rapide, aiguë et pétillante, ton électrique, crie de joie facilement.",
    lines: {
      start: ['Stream lancé, on speedrun !', "Allez, chat, on explose tout !", 'Néon en ligne, c\'est parti !', 'Full vitesse dès le départ !'],
      tempo: ['Ça accélère, trop bien !', 'Level up de vitesse, let\'s go !', 'Le chat devient fou !', 'Plus vite, plus de lumière !'],
      world: ['Nouveau monde, c\'est magnifique !', 'Warp réussi !', 'Regardez-moi ces couleurs !', 'Changement de zone, hype !'],
      parry: ['Parade, clip ça !', 'Contré, trop propre !', 'Réflexes de pro !', 'Frame perfect !', 'Zéro dégât, ez !'],
      boost: ['Boost, on passe en hyperdrive !', 'Vitesse lumière !', 'Ça fuse, ça fuse !'],
      coins: ['Combo de pièces, énorme !', 'On farm, on farm !', 'Pluie de pièces !'],
      fever: ['FRÉNÉSIE ! Mode néon total !', 'Tout brille, tout explose !', 'Overdrive activé !'],
      hit: ['Non, j\'ai pris un coup !', 'Aïe, ça c\'est du lag !', 'Oups, c\'est rien, on continue !', 'Aïe, focus, focus !'],
      lastLife: ['Dernière vie, le chat retient son souffle !', 'Mode hardcore activé !', 'Un cœur, zéro erreur !'],
      danger: ['Il est collé à moi, help !', 'Le curseur, le curseur !', 'Non, non, pas maintenant !', 'Faut que j\'accélère !'],
      escape: ['Ouf, on l\'a lâché !', 'Esquive de légende !', 'Bye bye, curseur !'],
      record: ['NOUVEAU RECORD, clip it !', 'Record mondial… enfin, le mien !', 'On a battu le record, chat !'],
      boss: ['Boss fight, préparez-vous !', 'Gros boss en vue, hype !', 'Oh, il est énorme !'],
      bossDown: ['Boss détruit, GG !', 'K.O. en direct !', 'Trop facile, next boss !'],
      bossEscaped: ['Il s\'est enfui, nul !', 'Rage quit du boss !'],
      fall: ['Noooon, je tombe !', 'Chute libre, au secours !'],
      over: ['Allez, run suivant !', 'On relance, j\'ai la dalle !', 'C\'était si proche, encore une !', 'Pas de pause, on y retourne !'],
      overRecord: ['Record ! Le chat en veut encore !', 'Nouveau record, on le repousse ?'],
    },
  },
  gold: {
    name: 'Doré',
    prompt: "Voix masculine grave et suave, arrogante et luxueuse, milliardaire vaniteux et théâtral, diction posée, très sûr de lui, un peu moqueur.",
    lines: {
      start: ['Place au dino le plus riche du web.', 'Courir ? Avec style, évidemment.', 'Mesdames, messieurs, admirez.', "L'or ne perd jamais."],
      tempo: ['Plus vite ? Enfin un défi.', 'Accélérons, le temps, c\'est de l\'argent.', 'Voilà une allure digne de moi.', 'Même à cette vitesse, je brille.'],
      world: ['Un nouveau domaine. Je l\'achète.', 'Hmm, charmant. Un peu pauvre.', 'Un monde à ma mesure, enfin.', 'Le décor change, mon éclat reste.'],
      parry: ['Pathétique.', 'Trop facile pour un dino en or.', 'On ne touche pas à l\'or.', 'Renvoyé. Sans pourboire.', 'Élégance absolue.'],
      boost: ['Jet privé activé.', 'Place, j\'arrive.', 'La vitesse, le luxe ultime.'],
      coins: ['Encore de l\'or ? Évidemment.', 'Mon compte en banque sourit.', 'Les pièces viennent à moi.'],
      fever: ['FRÉNÉSIE ! Contemplez ma splendeur !', 'Voici le vrai luxe !', 'Brillez, mes enfants !'],
      hit: ['Mon armure ! Rayée !', 'Comment osez-vous ?', 'Une simple égratignure.', 'Aïe. Mon avocat en entendra parler.'],
      lastLife: ['Dernière vie. Ne me décevez pas.', 'L\'or reste debout. Concentration.', 'Il est temps d\'être sérieux.'],
      danger: ['Ce curseur ose me suivre ?', 'Écartez ce vulgaire pointeur !', 'Vite, sauvez l\'or !', 'Il s\'approche de ma fortune !'],
      escape: ['Évidemment, il ne peut pas suivre.', 'Retourne dans ta barre des tâches.', 'Adieu, roturier.'],
      record: ['NOUVEAU RECORD. Comme prévu.', 'Un record en or massif.', 'Le sommet m\'appartient.'],
      boss: ['Un adversaire ? Voyons voir.', 'Enfin quelqu\'un à ma hauteur ?', 'Un boss. Comme c\'est mignon.'],
      bossDown: ['Vaincu. Suivant.', 'L\'or triomphe toujours.', 'Rangez-le avec les autres trophées.'],
      bossEscaped: ['Il fuit ma splendeur.', 'Il a eu peur. Normal.'],
      fall: ['Non ! Pas dans le vide !', 'Rattrapez-moi, je suis précieux !'],
      over: ['Encore. Je l\'exige.', 'Une légende ne s\'arrête pas là.', 'Relancez. Immédiatement.', 'Simple échauffement. On recommence.'],
      overRecord: ['Un record en or. Vous en voulez un autre ?', 'Magnifique. Faisons encore mieux.'],
    },
  },
  cursor: {
    name: 'Le Curseur',
    prompt: "Voix masculine grave et menaçante, froide et légèrement métallique, méchant de dessin animé qui ricane, diction lente et moqueuse.",
    lines: {
      taunt: ['Je vais fermer ton onglet…', 'Cours, petit dino. Cours.', 'Clic… clic… je te vois.', 'Tu ne peux pas m\'échapper.'],
      danger: ['Presque… presque…', 'Ta croix rouge t\'attend.', 'Plus que quelques pixels…', 'Je sens ta peur.'],
      caught: ['Clic. Onglet fermé.', 'Fin de session.', 'Fermé. Comme les autres.', 'Hahaha… au suivant.'],
      escape: ['Grr… tu ne perds rien pour attendre.', 'Profite, ça ne durera pas.'],
    },
  },
};
