// Personnages doublés (Gradium Voice Design, anglais) et leurs répliques par événement de course.
// Source unique : `npm run voices` génère public/voices/<perso>/<event>_<n>.mp3 + manifest.json.
// Répliques courtes (< 100 caractères) : ça doit claquer pendant la course, pas raconter une histoire.

export const LANGUAGE = 'en';

export const CHARACTERS = {
  reggae: {
    name: 'Riddim',
    prompt: 'A Jamaican male voice, 25 to 35, warm and sunny with a thick island accent, laid-back swinging rhythm, big smile, cool and very enthusiastic.',
    lines: {
      start: ['Yeah man, let\'s roll!', 'Feel the riddim, here we go!', 'The cursor wants me? Catch me if you can!', 'Riddim in the house, hold on tight!'],
      tempo: ['Speeding up, man! Keep the groove!', 'Tempo rising, feet flying!', 'Faster and hotter, yeah!', 'Oh, the bass hits harder now!'],
      world: ['New world, new vibes!', 'Wow, look at this place, man!', 'New scenery, same rhythm!', 'Sunshine teleport, yeah!'],
      parry: ['Dodge that, bye bye!', 'Too smooth for you, man!', 'Perfect parry, respect!', 'Sent you back home!', 'No pain, brother!'],
      boost: ['Reggae turbo, we flying!', 'Whoa, zoom zoom!', 'Hold on, here we go!'],
      coins: ['Raining coins, man!', 'Jackpot in the sun!', 'The coins love my groove!'],
      fever: ['FRENZY! Everybody dance!', 'Fire, man, fire!', 'Party mode on!'],
      hit: ['Ouch, that stings!', 'Oops, no worries, keep going!', 'Ow, stay cool, stay cool!', 'Get up, lion!'],
      lastLife: ['Last life, man, focus!', 'No more mistakes, just breathe!', 'All or nothing now, brother!'],
      danger: ['He\'s right behind, run!', 'The cursor\'s on me, go go go!', 'No no no, not my tab!', 'Faster, he\'s coming!'],
      escape: ['Phew, we lost him!', 'Too slow, mister cursor!', 'Breathe… we good.'],
      record: ['NEW RECORD, yeah man!', 'Record broken, the legend lives!', 'Further than ever, respect!'],
      boss: ['Oh, big one coming!', 'A boss? Let\'s make him dance!', 'Watch out, heavy vibes ahead!'],
      bossDown: ['Boss down, yeah!', 'Too strong for you, big boss!', 'Victory in the sun!'],
      bossEscaped: ['He ran away, next time!', 'Phew, he bailed!'],
      fall: ['Noooo, I\'m falling!', 'Oh no, the void, man!'],
      over: ['One more, man, let\'s go again!', 'No worries, next run is the one!', 'So close, run it back!', 'Come on, one more… then another!'],
      overRecord: ['Crazy record! Can you beat it? Go!', 'New record! Let\'s smash it again!'],
    },
  },
  classic: {
    name: 'Classic Dino',
    prompt: 'A young, slightly nasal male voice, mischievous and sarcastic like a retro 8-bit video game hero, fast talking and full of comic energy.',
    lines: {
      start: ['No internet? No problem. Go!', 'The offline dino is back in business!', 'Airplane mode, race mode!', 'You\'re not closing my tab!'],
      tempo: ['Is it getting faster? Oh yeah.', 'Next gear, pixel by pixel!', 'My tiny legs are burning!', 'More frames, more fun!'],
      world: ['Ooh, a new level!', 'Loading complete, keep going!', 'What is this world? I love it!', 'New map unlocked!'],
      parry: ['Parry! Too easy.', 'Blocked, like a captcha!', 'Error 404: attack not found!', 'Didn\'t even touch me!', 'Next!'],
      boost: ['Boost! Download accelerated!', 'Wooosh!', 'Fiber optic, baby!'],
      coins: ['Coins, coins, coins!', 'Coin combo, ding ding ding!', 'My wallet loves this!'],
      fever: ['FRENZY! Everything explodes!', '8-bit turbo mode!', 'Full overclock!'],
      hit: ['Ow! Bug!', 'Ouch, lag!', 'Hey, that wasn\'t in the patch notes!', 'Control Z, Control Z!'],
      lastLife: ['Low battery, last life!', 'One heart left, don\'t blow it!', 'Game over incoming, focus!'],
      danger: ['The cursor! It\'s gonna click!', 'Help, it\'s aiming for the X!', 'Run, run, run!', 'Not the red X, please!'],
      escape: ['Ha, missed me, cursor!', 'Lost you! Slow mouse.', 'Phew, game saved.'],
      record: ['NEW HIGH SCORE!', 'High score destroyed!', 'Record broken, screenshot it!'],
      boss: ['Boss incoming, save your game!', 'A wild boss appears!', 'Whoa, big sprite!'],
      bossDown: ['Boss defeated! Achievement unlocked!', 'K.O.!', 'Boss deleted!'],
      bossEscaped: ['He ran away, coward!', 'He closed his own tab.'],
      fall: ['Aaaah, out of bounds!', 'No floor? Seriously?'],
      over: ['Try again? Obviously!', 'Hit space, let\'s go again!', 'So close, one more!', 'Game over… for five seconds!'],
      overRecord: ['High score! Can you beat it again?', 'Record! Come on, one more run!'],
    },
  },
  neon: {
    name: 'Neon',
    prompt: 'A young female voice, hyper energetic cyberpunk gaming streamer, very fast paced, bright and bubbly, electric tone, screams with joy easily.',
    lines: {
      start: ['Stream is live, let\'s speedrun!', 'Okay chat, let\'s wreck this!', 'Neon online, let\'s go!', 'Full speed from the start!'],
      tempo: ['It\'s speeding up, love it!', 'Speed level up, let\'s go!', 'Chat is going crazy!', 'Faster, brighter!'],
      world: ['New world, it\'s gorgeous!', 'Warp successful!', 'Look at these colors!', 'New zone, hype!'],
      parry: ['Parry, clip that!', 'Countered, so clean!', 'Pro reflexes!', 'Frame perfect!', 'Zero damage, easy!'],
      boost: ['Boost, hyperdrive time!', 'Light speed!', 'Zoom zoom zoom!'],
      coins: ['Coin combo, huge!', 'Farming, farming!', 'It\'s raining coins!'],
      fever: ['FRENZY! Full neon mode!', 'Everything\'s glowing!', 'Overdrive activated!'],
      hit: ['No, I got hit!', 'Ow, that\'s lag!', 'Oops, it\'s fine, keep going!', 'Ouch, focus, focus!'],
      lastLife: ['Last life, chat, hold your breath!', 'Hardcore mode on!', 'One heart, zero mistakes!'],
      danger: ['It\'s right on me, help!', 'The cursor, the cursor!', 'No, no, not now!', 'I gotta go faster!'],
      escape: ['Phew, we lost it!', 'Legendary dodge!', 'Bye bye, cursor!'],
      record: ['NEW RECORD, clip it!', 'World record… well, mine!', 'We beat the record, chat!'],
      boss: ['Boss fight, get ready!', 'Huge boss incoming, hype!', 'Oh, it\'s massive!'],
      bossDown: ['Boss destroyed, GG!', 'Live K.O.!', 'Too easy, next boss!'],
      bossEscaped: ['It ran away, lame!', 'Boss rage quit!'],
      fall: ['Noooo, I\'m falling!', 'Free fall, help!'],
      over: ['Okay, next run!', 'Run it back, I\'m hungry!', 'That was so close, one more!', 'No breaks, let\'s go again!'],
      overRecord: ['Record! Chat wants more!', 'New record, let\'s push it further?'],
    },
  },
  gold: {
    name: 'Golden',
    prompt: 'A deep, smooth male voice, arrogant and luxurious, a vain theatrical billionaire, slow and poised delivery, extremely self-assured and a bit mocking.',
    lines: {
      start: ['Make way for the richest dino on the web.', 'Running? With style, naturally.', 'Ladies and gentlemen, behold.', 'Gold never loses.'],
      tempo: ['Faster? Finally, a challenge.', 'Speed up, time is money.', 'Now that is a pace worthy of me.', 'Even at this speed, I shine.'],
      world: ['A new estate. I\'ll buy it.', 'Hmm, charming. A bit cheap.', 'A world worthy of me, at last.', 'The scenery changes, my shine remains.'],
      parry: ['Pathetic.', 'Too easy for a golden dino.', 'Nobody touches the gold.', 'Returned. No tip.', 'Absolute elegance.'],
      boost: ['Private jet engaged.', 'Step aside, I\'m coming through.', 'Speed, the ultimate luxury.'],
      coins: ['More gold? Of course.', 'My bank account is smiling.', 'Coins come to me.'],
      fever: ['FRENZY! Behold my splendor!', 'This is true luxury!', 'Shine, my children!'],
      hit: ['My armor! Scratched!', 'How dare you?', 'A mere scratch.', 'Ow. My lawyer will hear about this.'],
      lastLife: ['Last life. Do not disappoint me.', 'Gold stands tall. Focus.', 'Time to get serious.'],
      danger: ['This cursor dares to follow me?', 'Get that vulgar pointer away!', 'Quick, save the gold!', 'It\'s approaching my fortune!'],
      escape: ['Naturally, it can\'t keep up.', 'Back to your taskbar.', 'Farewell, peasant.'],
      record: ['NEW RECORD. As expected.', 'A solid gold record.', 'The summit belongs to me.'],
      boss: ['An opponent? Let\'s see.', 'Finally someone at my level?', 'A boss. How adorable.'],
      bossDown: ['Defeated. Next.', 'Gold always triumphs.', 'Put it with the other trophies.'],
      bossEscaped: ['It flees my splendor.', 'It got scared. Understandable.'],
      fall: ['No! Not into the void!', 'Catch me, I\'m precious!'],
      over: ['Again. I insist.', 'A legend doesn\'t stop here.', 'Restart. Immediately.', 'Just a warm-up. Once more.'],
      overRecord: ['A golden record. Care for another?', 'Magnificent. Let\'s do even better.'],
    },
  },
  cursor: {
    name: 'The Cursor',
    prompt: 'A deep, menacing male voice, cold and slightly metallic, a cartoon villain who snickers, slow and mocking delivery.',
    lines: {
      taunt: ['I\'m going to close your tab…', 'Run, little dino. Run.', 'Click… click… I see you.', 'You can\'t escape me.'],
      danger: ['Almost… almost…', 'Your red X awaits.', 'Just a few more pixels…', 'I can smell your fear.'],
      caught: ['Click. Tab closed.', 'Session ended.', 'Closed. Like all the others.', 'Hahaha… next.'],
      escape: ['Grr… you can\'t run forever.', 'Enjoy it while it lasts.'],
    },
  },
};
